name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/cert_bot_auto_renew && mv target/release/cert_bot_auto_renew target/release/cert_bot_auto_renew_linux_amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cert_bot_auto_renew-linux-amd64
          path: target/release/cert_bot_auto_renew_linux_amd64
  build-linux-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install Cross
        run: cargo install cross

      - name: Build
        run: cross build --all --release --target aarch64-unknown-linux-gnu && strip target/release/cert_bot_auto_renew && mv target/aarch64-unknown-linux-gnu/release/cert_bot_auto_renew target/aarch64-unknown-linux-gnu/release/cert_bot_auto_renew_linux_arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cert_bot_auto_renew-linux-amd64
          path: target/aarch64-unknown-linux-gnu/release/cert_bot_auto_renew_linux_arm64

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        name: ⚡ Cache
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cert_bot_auto_renew-win
          path: target/release/cert_bot_auto_renew.exe

  build-mac-intel:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        name: ⚡ Cache
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for Mac Intel
        run: cargo build --all --release && strip target/release/cert_bot_auto_renew && mv target/release/cert_bot_auto_renew target/release/cert_bot_auto_renew_darwin_intel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cert_bot_auto_renew-darwin-intel
          path: target/release/cert_bot_auto_renew_darwin_intel

  build-mac-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        name: ⚡ Cache
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: Build for Apple Silicon
        run: cargo build --all --release --target aarch64-apple-darwin && strip target/aarch64-apple-darwin/release/cert_bot_auto_renew && mv target/aarch64-apple-darwin/release/cert_bot_auto_renew target/release/cert_bot_auto_renew_darwin_arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cert_bot_auto_renew-darwin-arm64
          path: target/release/cert_bot_auto_renew_darwin_arm64